apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus-configmap.yaml
  - prometheus-pvc.yaml
  - prometheus-deployment.yaml
  - prometheus-service.yaml
  - grafana-secret.yaml
  - grafana-configmap.yaml
  - grafana-dashboard-configmap.yaml
  - grafana-pvc.yaml
  - grafana-deployment.yaml
  - grafana-service.yaml

# 可选: 添加通用标签
commonLabels:
  app.kubernetes.io/name: monitoring
  app.kubernetes.io/component: prometheus-grafana
